table OceanSun
	lineageTag: 277ee8e9-e66b-4fee-bc8f-667d4082880c

	column Xmean_cog
		dataType: double
		lineageTag: b0f7f3e6-72db-43a4-b3a7-fe8468857bc2
		summarizeBy: sum
		sourceColumn: Xmean_cog

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Xmax_cog
		dataType: double
		lineageTag: f43d4d19-95ce-4367-8aa5-752741a6d649
		summarizeBy: sum
		sourceColumn: Xmax_cog

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Xmin_cog
		dataType: double
		lineageTag: 81394b4b-bcd6-478a-8577-853016befbf1
		summarizeBy: sum
		sourceColumn: Xmin_cog

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Ymean_cog
		dataType: double
		lineageTag: d2f6b70b-bdcc-4025-ab04-995a455192e8
		summarizeBy: sum
		sourceColumn: Ymean_cog

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Ymax_cog
		dataType: double
		lineageTag: e7e1cd0d-c1ea-4c9c-92ed-a88bdf1d484d
		summarizeBy: sum
		sourceColumn: Ymax_cog

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Ymin_cog
		dataType: double
		lineageTag: 9f2b982b-2093-4e25-8549-47a1fb78e92f
		summarizeBy: sum
		sourceColumn: Ymin_cog

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Zmean_cog
		dataType: double
		lineageTag: 6cde53f0-773a-42ea-bf8d-080156fd0102
		summarizeBy: sum
		sourceColumn: Zmean_cog

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Zmax_cog
		dataType: double
		lineageTag: dc90cdd4-f671-431d-81d8-214b5e21e448
		summarizeBy: sum
		sourceColumn: Zmax_cog

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Zmin_cog
		dataType: double
		lineageTag: 604d571a-3eab-485d-bcf3-6a49e7912eba
		summarizeBy: sum
		sourceColumn: Zmin_cog

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Rollmean
		dataType: double
		lineageTag: 75beb57b-ed70-4eff-b3ee-bba736bd5b9a
		summarizeBy: sum
		sourceColumn: Rollmean

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Rollmax
		dataType: double
		lineageTag: 7eec4ad6-d7a2-4b08-a13e-8b16cb0edb45
		summarizeBy: sum
		sourceColumn: Rollmax

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Rollmin
		dataType: double
		lineageTag: 1d1c9365-83e8-4f99-90a3-68f572b3ac32
		summarizeBy: sum
		sourceColumn: Rollmin

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Pitchmean
		dataType: double
		lineageTag: 6f09cc05-9c35-4ad0-84aa-90765e99aded
		summarizeBy: sum
		sourceColumn: Pitchmean

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Pitchmax
		dataType: double
		lineageTag: cf3b0cd5-e758-4bd0-a4f6-779df8faba44
		summarizeBy: sum
		sourceColumn: Pitchmax

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Pitchmin
		dataType: double
		lineageTag: 26b83c8d-9313-4c24-8ce2-793fab257445
		summarizeBy: sum
		sourceColumn: Pitchmin

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Yawmean
		dataType: double
		lineageTag: 53abd8db-b08d-4135-8664-ab6c818980f7
		summarizeBy: sum
		sourceColumn: Yawmean

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column LC1mean
		dataType: double
		lineageTag: 8b4870e5-7f16-44be-8eb0-f1a5851ea79f
		summarizeBy: sum
		sourceColumn: LC1mean

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column LC1max
		dataType: double
		lineageTag: 9a9e6450-0c87-483d-a433-20c5a9d0f430
		summarizeBy: sum
		sourceColumn: LC1max

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column LC1min
		dataType: double
		lineageTag: fc1206ee-d59a-4e74-affc-83d9783807cf
		summarizeBy: sum
		sourceColumn: LC1min

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column LC2mean
		dataType: double
		lineageTag: 1656a416-d1ef-4d6d-b63f-78d8f53c1fa9
		summarizeBy: sum
		sourceColumn: LC2mean

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column LC2max
		dataType: double
		lineageTag: e24ce4d9-2d71-4380-b149-e17f0251531d
		summarizeBy: sum
		sourceColumn: LC2max

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column LC2min
		dataType: double
		lineageTag: 58e92543-9d25-42ef-845f-21428567dee6
		summarizeBy: sum
		sourceColumn: LC2min

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column LC3mean
		dataType: double
		lineageTag: 4f55bead-7631-4527-a7ac-58da9a8e98ad
		summarizeBy: sum
		sourceColumn: LC3mean

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column LC3max
		dataType: double
		lineageTag: 5f7db377-8c82-455e-8384-765c614e166b
		summarizeBy: sum
		sourceColumn: LC3max

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column LC3min
		dataType: double
		lineageTag: 8d2881f5-c7ce-402e-9c42-fee0e5981d85
		summarizeBy: sum
		sourceColumn: LC3min

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column LC4mean
		dataType: double
		lineageTag: b68bc68c-6edf-4942-a1eb-d45927043748
		summarizeBy: sum
		sourceColumn: LC4mean

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column LC4max
		dataType: double
		lineageTag: 32d9e13f-26d7-42d4-a4ee-b402b7a7b1b7
		summarizeBy: sum
		sourceColumn: LC4max

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column LC4min
		dataType: double
		lineageTag: 183c474a-f82b-4891-ae8d-41db8d8a76f0
		summarizeBy: sum
		sourceColumn: LC4min

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column LC5mean
		dataType: double
		lineageTag: 65de183c-19a6-4c19-8dc5-e8cf2a28aec5
		summarizeBy: sum
		sourceColumn: LC5mean

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column LC5max
		dataType: double
		lineageTag: 6c5cd2f3-3269-4e90-87c1-ceff3a1360b9
		summarizeBy: sum
		sourceColumn: LC5max

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column LC5min
		dataType: double
		lineageTag: fbd365b4-311b-46ae-9e84-ae418c053735
		summarizeBy: sum
		sourceColumn: LC5min

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column LC6mean
		dataType: double
		lineageTag: 7914706b-4d51-42af-9fda-8c7140fe346d
		summarizeBy: sum
		sourceColumn: LC6mean

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column LC6max
		dataType: double
		lineageTag: 8a5e062f-5418-4a1d-951d-9502105feba6
		summarizeBy: sum
		sourceColumn: LC6max

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column LC6min
		dataType: double
		lineageTag: f0b42d03-c162-4b50-8b6f-931d2b3eb27f
		summarizeBy: sum
		sourceColumn: LC6min

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Fecha
		dataType: dateTime
		formatString: General Date
		lineageTag: 70f14eaa-72d3-452e-9e4e-2ec732a65c30
		summarizeBy: none
		sourceColumn: Fecha

		variation Variación
			isDefault
			relationship: d79b4355-5dbb-4def-9ff5-9a467d7c0d1e
			defaultHierarchy: LocalDateTable_dfb055c0-3e2f-431a-ad77-77c473300a1b.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column Periodo
		dataType: string
		lineageTag: afa608a6-fee0-4b8c-a0e1-bc62ed7d3011
		summarizeBy: none
		sourceColumn: Periodo

		annotation SummarizationSetBy = Automatic

	column source_file
		dataType: string
		lineageTag: 8f2f91dc-3368-40ee-8bae-bf91f50c9d08
		summarizeBy: none
		sourceColumn: source_file

		annotation SummarizationSetBy = Automatic

	partition OceanSun = m
		mode: import
		source =
				let
				    Origen = Value.NativeQuery(Databricks.Catalogs(host, http, [Catalog=catalogo, Database=null, EnableAutomaticProxyDiscovery=null, Implementation=null]){[Name="precatalog",Kind="Database"]}[Data], "SELECT * FROM precatalog.samat_silver.slv_samat_sierrabrava_oceansun", null, [EnableFolding=true]),
				    //Origen = Value.NativeQuery(Databricks.Catalogs(host, http, [Catalog=catalogo, Database=null, EnableAutomaticProxyDiscovery=null]){[Name="precatalog",Kind="Database"]}[Data], "SELECT * FROM precatalog.samat_silver.slv_samat_sierrabrava_oceansun", null, [EnableFolding=true]),
				    #"Columnas quitadas" = Table.RemoveColumns(Origen,{"datalake_load_date", "datalake_load_day", "datalake_ingestion_uuid"}),
				    #"Dividir columna por delimitador" = Table.SplitColumn(#"Columnas quitadas", "Date", Splitter.SplitTextByEachDelimiter({"_"}, QuoteStyle.None, false), {"Date.1", "Date.2"}),
				    #"Dividir columna por delimitador1" = Table.SplitColumn(#"Dividir columna por delimitador", "Date.2", Splitter.SplitTextByDelimiter("_", QuoteStyle.Csv), {"Date.2.1", "Date.2.2"}),
				    #"Tipo cambiado2" = Table.TransformColumnTypes(#"Dividir columna por delimitador1",{{"Date.1", type date}}),
				    #"Columnas quitadas1" = Table.RemoveColumns(#"Tipo cambiado2",{"Date.2.1"}),
				    #"Columnas con nombre cambiado" = Table.RenameColumns(#"Columnas quitadas1",{{"Date.1", "Fecha"}}),
				    #"Personalizada agregada" = Table.AddColumn(#"Columnas con nombre cambiado", "Hora", each Text.Combine({[Date.2.2], ":00"})),
				    #"Tipo cambiado1" = Table.TransformColumnTypes(#"Personalizada agregada",{{"Hora", type time}}),
				    #"Columnas quitadas2" = Table.RemoveColumns(#"Tipo cambiado1",{"Date.2.2"}),
				    #"Semana del año insertada" = Table.AddColumn(#"Columnas quitadas2", "Periodo", each Text.From(Date.WeekOfYear([Fecha])) & " - " & Text.From(Date.Year([Fecha]))),
				    #"Columnas combinadas" = Table.CombineColumns(Table.TransformColumnTypes(#"Semana del año insertada", {{"Fecha", type text}, {"Hora", type text}}, "es-ES"),{"Fecha", "Hora"},Combiner.CombineTextByDelimiter(" ", QuoteStyle.None),"Fecha"),
				    #"Tipo cambiado3" = Table.TransformColumnTypes(#"Columnas combinadas",{{"Fecha", type datetime}}),
				    #"Columnas reordenadas" = Table.ReorderColumns(#"Tipo cambiado3",{"Fecha", "Xmean_cog", "Xmax_cog", "Xmin_cog", "Ymean_cog", "Ymax_cog", "Ymin_cog", "Zmean_cog", "Zmax_cog", "Zmin_cog", "Rollmean", "Rollmax", "Rollmin", "Pitchmean", "Pitchmax", "Pitchmin", "Yawmean", "LC1mean", "LC1max", "LC1min", "LC2mean", "LC2max", "LC2min", "LC3mean", "LC3max", "LC3min", "LC4mean", "LC4max", "LC4min", "LC5mean", "LC5max", "LC5min", "LC6mean", "LC6max", "LC6min", "Periodo"}),
				    #"Filas ordenadas" = Table.Sort(#"Columnas reordenadas",{{"Fecha", Order.Ascending}})
				in
				    #"Filas ordenadas"

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

